Repository 9weeks-app-web/team-3-sfacfolio, pull requests merged in 2024-01, with the labels that each got.

#11 Feat/#5/find 프로젝트 섹션
  app/(route)/main/(components)/(RealTime)/RealTimeCommunityItem.tsx
  app/(route)/main/(components)/(RealTime)/RealTimeKeyword.tsx
  app/(route)/main/(components)/(RealTime)/RealTimeKeywordItem.tsx
  app/(route)/main/(components)/Card/PortfoiloCard/PortfolioCardFooter/PortfolioCardFooter.tsx
  app/(route)/main/(components)/CategoryButtonWrap.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCard.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCardLabel.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectTag.tsx
  app/(route)/main/(components)/MoreButton/MoreButton.tsx
  app/(route)/main/(components)/SectionHeader.tsx
  app/(route)/main/page.tsx
  app/components/Footer/Footer.tsx
  app/components/Footer/SocialIcons.tsx
  app/page.tsx
  next.config.js
  public/assets/images/ArrowDown.svg
  public/assets/images/Eye.svg
  public/assets/images/Heart.svg
  tsconfig.json
Labels: feat, refactor, chore, style

#13 Feat: 메인페이지 레이아웃 및 컴포넌트 배치
  app/(route)/main/(components)/(BannerCarousel)/BannerCarousel.tsx
  app/(route)/main/(components)/(RealTime)/RealTimeCommunity.tsx
  app/(route)/main/(components)/(RealTime)/RealTimeContainer.tsx
  app/(route)/main/(components)/ABTest.tsx
  app/(route)/main/(components)/Card/Card.tsx
  app/(route)/main/(components)/Card/CardContainer.tsx
  app/(route)/main/(components)/CategoryButton.tsx
  app/(route)/main/(components)/CategoryButtonWrap.tsx
  app/(route)/main/(components)/MoreButton/MoreButton.tsx
  app/(route)/main/(components)/SectionHeader.tsx
  app/(route)/main/(components)/SectionWrapper.tsx
  app/(route)/main/page.tsx
  app/components/Container.tsx
  app/components/Footer/Footer.tsx
  app/components/Header.tsx
  app/page.tsx
  app/utils/index.ts
Labels: feat, update, refactor, style

#14 Feat/#5/find 프로젝트 섹션
  app/(route)/main/(components)/FindProjectCard/FindProjectCard.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCarousel.tsx
  app/(route)/main/(components)/FindProjectCard/ProjectMatchingBanner.tsx
  app/style/findProjectCarousle.module.css
  public/assets/images/CaretCircleRight.svg
  public/assets/images/Rocket.svg
Labels: feat, refactor

#15 Feat/#3/배너 캐러셀 디자인 수정
  app/(route)/main/(components)/(BannerCarousel)/BannerCarousel.tsx
  app/style/bannerCarousel.module.css
Labels: style

#17 Feat/#5/find 프로젝트 섹션
  app/components/Header.tsx
  app/components/Header/FolioHeader.tsx
  app/components/Header/FolioHeaderInput.tsx
  app/components/Header/Header.tsx
  app/components/Header/LoginButton.tsx
  public/assets/images/LogoFolio.svg
  public/assets/images/LogoLog.svg
  public/assets/images/LogoS.svg
  public/assets/images/Search.svg
Labels: etc, feat

#26 Feat/#19/프로젝트-상세-페이지
  app/(route)/main/(components)/Card/PortfoiloCard/PortfolioCardFooter/PortfolioCardFooter.tsx
  app/(route)/main/(components)/CategoryButtonWrap.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCard.tsx
  app/(route)/main/(components)/SectionHeader.tsx
  app/(route)/project/[id]/(components)/Comments/CommentsBox.tsx
  app/(route)/project/[id]/(components)/Comments/CommentsListWrap.tsx
  app/(route)/project/[id]/(components)/Comments/CommentsWrap.tsx
  app/(route)/project/[id]/(components)/Comments/ReplyBox.tsx
  app/(route)/project/[id]/(components)/FixedLayer.tsx
  app/(route)/project/[id]/(components)/Project/ProjectApplication.tsx
  app/(route)/project/[id]/(components)/Project/ProjectDescription.tsx
  app/(route)/project/[id]/(components)/Project/ProjectDetails.tsx
  app/(route)/project/[id]/(components)/Project/ProjectInfoLabel.tsx
  app/(route)/project/[id]/(components)/Project/ProjectInfoTag.tsx
  app/(route)/project/[id]/(components)/Project/ProjectInfoText.tsx
  app/(route)/project/[id]/(components)/Project/ProjectSectionTitle.tsx
  app/(route)/project/[id]/page.tsx
  app/api/project.ts
  app/components/HeartIcon.tsx
  app/components/Loader.tsx
  app/components/ProfileImage.tsx
  app/components/Provider.tsx
  app/types/project.ts
  app/utils/dateUtils.ts
  app/utils/firebase.ts
  package-lock.json
  package.json
  public/assets/images/IconHeart.svg
  public/assets/images/IconLink.svg
  public/assets/images/IconProjectHeart.svg
  public/assets/images/IconShare.svg
  public/assets/images/ProjectDefaultThumbnail.svg
  public/assets/images/index.ts
Labels: feat

#27 Feat/#22/프로젝트 목록 페이지
  app/(route)/project/(components)/ProjectBanner/ProjectBanner.tsx
  app/(route)/project/(components)/common/ProjectButton.tsx
  app/components/Header/FolioHeader.tsx
  app/page.tsx
  public/assets/images/BusinessStrategy.svg
  public/assets/images/Close.svg
Labels: feat

#33 Feat/#29/채용페이지-필터-모달
  app/(route)/career/company/(component)/LocationItem.tsx
  app/(route)/career/company/(component)/ModalCategory.tsx
  app/(route)/career/company/(component)/ModalHeader.tsx
  app/(route)/career/company/(component)/ModalJob.tsx
  app/(route)/career/company/(component)/ModalLayout.tsx
  app/(route)/career/company/(component)/ModalLocations.tsx
  app/(route)/career/company/(component)/ModalTech.tsx
  app/(route)/career/company/(component)/ModalYears.tsx
  app/(route)/career/company/page.tsx
  app/(route)/main/(components)/Card/PortfoiloCard/PortfolioCardFooter/PortfolioCardFooter.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCard.tsx
  app/(route)/project/[id]/(components)/Comments/CommentsBox.tsx
  app/(route)/project/[id]/(components)/Comments/ReplyBox.tsx
  app/(route)/project/[id]/(components)/FixedLayer.tsx
  app/components/Footer/Footer.tsx
  app/components/Footer/FooterInfo.tsx
  app/components/Header/FolioHeader.tsx
  app/components/Icons/BookIcon.tsx
  app/components/Icons/BoxIcon.tsx
  app/components/Icons/CameraIcon.tsx
  app/components/Icons/CategoryIcon.tsx
  app/components/Icons/GamepadIcon.tsx
  app/components/Icons/GraphIcon.tsx
  app/components/Icons/HeartIcon.tsx
  app/components/Icons/LaptopIcon.tsx
  app/components/Icons/ScaleIcon.tsx
  app/components/Icons/ScreenIcon.tsx
  app/components/Icons/VideoIcon.tsx
  app/constants/locations.ts
  app/style/globals.css
  app/style/rc-slider.css
  package-lock.json
  package.json
  public/assets/images/IconCategoryDelete.svg
  public/assets/images/IconClose.svg
  public/assets/images/IconReset.svg
  tailwind.config.ts
Labels: feat

#34 Feat/#28/채용 상세 페이지
  app/(route)/career/company/[id]/(components)/CompanyInfo/CompanyInfo.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailCarousel.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailKeyword.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailLocation.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailNavigation.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailSection.tsx
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailText.tsx
  app/(route)/career/company/[id]/(components)/CompanySticky/CompanyDetailButton.tsx
  app/(route)/career/company/[id]/(components)/CompanySticky/CompanyDetailLink.tsx
  app/(route)/career/company/[id]/(components)/CompanySticky/CompanyDetailRange.tsx
  app/(route)/career/company/[id]/(components)/CompanySticky/CompanySticky.tsx
  app/(route)/career/company/[id]/page.tsx
  app/api/hire.ts
  app/components/ArrowLeftIcon.tsx
  app/components/ArrowRightIcon.tsx
  app/components/BookmarkIcon.tsx
  app/components/CompanyBagIcon.tsx
  app/components/LocationIcon.tsx
  app/components/PlusIcon.tsx
  app/constants/index.ts
  app/hooks/useSectionMove.ts
  app/types/hire.ts
  public/assets/images/BannerImage.png
Labels: feat

#38 Feat/#30/채용 테크 커리어 페이지
  app/(route)/career/tech/page.tsx
  app/components/Header/FolioHeader.tsx
  app/components/Header/Header.tsx
  public/assets/images/TechBanner.svg
Labels: feat, style

#41 Feat/#30/채용 테크 커리어 페이지
  app/(route)/career/company/(component)/CompanyFilterButton.tsx
  app/(route)/career/company/(component)/ModalLocations.tsx
  app/(route)/career/company/page.tsx
  app/(route)/career/tech/page.tsx
  app/utils/companyFilterUtils.ts
Labels: bug, feat

#40 Feat/#36/mypage-setting
  app/(route)/career/page.tsx
  app/(route)/mypage/@modal/(.)profileImage/page.tsx
  app/(route)/mypage/@modal/default.tsx
  app/(route)/mypage/default.tsx
  app/(route)/mypage/layout.tsx
  app/(route)/mypage/page.tsx
  app/(route)/mypage/profileImage/page.tsx
  app/(route)/mypage/setting/(components)/SettingToggle.tsx
  app/(route)/mypage/setting/(components)/SettingWrap.tsx
  app/(route)/mypage/setting/(components)/ToggleSwitch.tsx
  app/(route)/mypage/setting/page.tsx
  app/components/Icons/CameraIcon.tsx
  next.config.js
  public/assets/images/IconSwap.svg
Labels: feat

#42 Feat/#37/마이페이지 커리어페이지 이력서 관리
  app/(route)/mypage/(components)/Resume/AdditionalResume.tsx
  app/(route)/mypage/(components)/Resume/RequiredResume.tsx
  app/(route)/mypage/(components)/Resume/Resume.tsx
  app/(route)/mypage/(components)/Resume/ResumeButton.tsx
  app/(route)/mypage/(components)/Resume/ResumeHeader.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeChangingInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeLabelList.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumePeriodInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeRadioInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeSearchInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeSelectInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeTextArea.tsx
  app/(route)/mypage/(components)/Resume/ResumeInput/ResumeTextInput.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeAbilitySection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeBasicInformationSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeCareerSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeExperienceSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeIntroductionSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumePortfolioSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ResumeSection.tsx
  app/(route)/mypage/(components)/Resume/ResumeSection/ReusumeAcademicSection.tsx
  public/assets/images/CirclePlus.svg
  public/assets/images/IconPlus.svg
  public/assets/images/InputArrowDown.svg
Labels: feat

#46 Feat: Google Map 적용
  app/(route)/career/company/[id]/(components)/CompanyInfo/Section/CompanyDetailLocation.tsx
  app/types/hire.ts
Labels: feat

#47 Feat/#24/포트폴리오 상세 페이지
  app/(route)/portfolio/@modal/(.)[id]/page.tsx
  app/(route)/portfolio/@modal/default.tsx
  app/(route)/portfolio/[id]/(components)/Modal.tsx
  app/(route)/portfolio/[id]/page.tsx
Labels: feat

#50 Feat/#45/커뮤니티-메인페이지
  app/(route)/community/(components)/CommunityBanner.tsx
  app/(route)/community/(components)/CommunityMenu.tsx
  app/(route)/community/(components)/CommunityPagination.tsx
  app/(route)/community/(components)/CommunityPostBox.tsx
  app/(route)/community/(components)/CommunityPostList.tsx
  app/(route)/community/(components)/CommunitySearch.tsx
  app/(route)/community/(components)/CommunityTag.tsx
  app/(route)/community/page.tsx
  app/(route)/main/(components)/(RealTime)/RealTimeKeyword.tsx
  app/(route)/main/(components)/FindProjectCard/FindProjectCard.tsx
  app/(route)/main/page.tsx
  app/(route)/project/(components)/ProjectBanner/ProjectBanner.tsx
  app/(route)/project/[id]/page.tsx
  app/api/community.ts
  app/components/Icons/EyeIcon.tsx
  app/components/Icons/PlusIcon.tsx
  app/components/RealTime/RealTimeCommunity.tsx
  app/components/RealTime/RealTimeCommunityItem.tsx
  app/components/RealTime/RealTimeContainer.tsx
  app/components/RealTime/RealTimeKeyword.tsx
  app/components/RealTime/RealTimeKeywordItem.tsx
  app/dummy/index.ts
  app/style/community.module.css
  app/types/index.ts
  app/utils/dateUtils.ts
  public/assets/images/Close.svg
  public/assets/images/CommunityBanner.svg
  public/assets/images/Eye.svg
  public/assets/images/IconEdit.svg
  public/assets/images/IconMessage.svg
Labels: feat

#51 Feat/#49/메인페이지-커뮤니티섹션-스팩퀴즈섹션
  app/(route)/community/(components)/CommunityPostBox.tsx
  app/(route)/community/page.tsx
  app/(route)/main/(components)/ABTest.tsx
  app/(route)/main/(components)/SpacQuiz/SpacQuizWrap.tsx
  app/(route)/main/(components)/SpacQuizBox.tsx
  app/(route)/main/page.tsx
  app/components/RealTime/RealTimeCommunity.tsx
  app/components/RealTime/RealTimeCommunityItem.tsx
  app/components/RealTime/RealTimeContainer.tsx
  app/components/RealTime/RealTimeKeyword.tsx
  app/components/RealTime/RealTimeKeywordItem.tsx
  app/dummy/index.ts
  public/assets/images/ABtest_A.png
  public/assets/images/ABtest_B.png
  public/assets/images/SpacQuiz1.png
  public/assets/images/SpacQuiz2.png
  public/assets/images/SpacQuiz3.png
  public/assets/images/SpacQuiz4.png
Labels: feat, update

#55 Feat/#45/커뮤니티-메인페이지
  app/(route)/community/(components)/CommunityPagination.tsx
  app/(route)/community/(components)/CommunityPostList.tsx
  app/(route)/community/(components)/CommunityWriteButton.tsx
  app/constants/index.ts
  public/assets/images/IconEdit.svg
Labels: feat, update, style

#53 Feat/#24/포트폴리오 상세 페이지
  app/(route)/portfolio/@modal/(.)[id]/page.tsx
  app/(route)/portfolio/[id]/(components)/Modal.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioDetail/PortfolioDetail.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioDetail/PortfolioDetailFooter.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioDetail/PortfolioDetailHeader.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioDetail/PortfolioOwnerCard.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioDetail/PortfolioOwnerCardSlider.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfoliIoInfoTools.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfolioInfo.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfolioInfoComments.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfolioInfoHeader.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfolioInfoTags.tsx
  app/(route)/portfolio/[id]/(components)/PortfolioInfo/PortfolioinfoLevel.tsx
  app/(route)/portfolio/[id]/page.tsx
  app/components/HeartIcon.tsx
  app/style/ProtfolioOwnerCarousel.module.css
  public/assets/images/ArrowDownFull.svg
  public/assets/images/CloseIcon.svg
  public/assets/images/Comment.svg
  public/assets/images/Copyright1.svg
  public/assets/images/Copyright2.svg
  public/assets/images/Copyright3.svg
  public/assets/images/Copyright4.svg
  public/assets/images/EllipsisVertical.svg
  public/assets/images/Portfolio/Portfolio.png
  public/assets/images/Portfolio/Portfolio_thumb_1.png
  public/assets/images/Portfolio/Portfolio_thumb_2.png
  public/assets/images/Portfolio/Portfolio_thumb_3.png
  public/assets/images/Portfolio/Portfolio_thumb_4.png
  public/assets/images/Tools/Figma.svg
  public/assets/images/Tools/Illustrator.svg
  public/assets/images/Tools/Photoshop.svg
  public/assets/images/Tools/Premiere.svg
Labels: feat

#56 Feat/#54/메인페이지 상단 배너 디자인 및 기능 수정
  app/(route)/main/(components)/(BannerCarousel)/BannerCarousel.tsx
  app/style/bannerCarousel.module.css
  public/assets/images/Pause.svg
  public/assets/images/Start.svg
Labels: feat, style

#58 Feat/#43/프로필 컴포넌트
  app/(route)/mypage/(components)/MyProfile.tsx
  app/(route)/mypage/(components)/ProfileButton.tsx
  app/(route)/mypage/(components)/ProfileDetail.tsx
  app/(route)/mypage/(components)/ProfileItem.tsx
  app/(route)/mypage/(components)/ProfileSummary.tsx
  app/(route)/mypage/(components)/ProfileTab.tsx
  app/(route)/mypage/(components)/ProfileUtilButton.tsx
  app/(route)/mypage/page.tsx
  public/assets/images/Camera.svg
  public/assets/images/ProfileBackground.svg
  public/assets/images/Setting.svg
  public/assets/images/Share.svg
Labels: feat, refactor

#62 Feat/#57/AB퀴즈-메인페이지
  app/(route)/community/page.tsx
  app/(route)/main/(components)/SpacQuiz/SpacQuizWrap.tsx
  app/(route)/quiz/(components)/Banner.tsx
  app/(route)/quiz/(components)/SpacQuizBox.tsx
  app/(route)/quiz/page.tsx
  app/api/community.ts
  app/api/spacQuiz.ts
  app/components/DropDownFilter.tsx
  app/components/Pagination.tsx
  app/dummy/community.ts
  app/dummy/index.ts
  app/dummy/spacQuiz.ts
  public/assets/images/SpacQuiz/BannerImage.svg
  public/assets/images/SpacQuiz/SpacQuiz1.png
  public/assets/images/SpacQuiz/SpacQuiz10.png
  public/assets/images/SpacQuiz/SpacQuiz11.png
  public/assets/images/SpacQuiz/SpacQuiz12.png
  public/assets/images/SpacQuiz/SpacQuiz2.png
  public/assets/images/SpacQuiz/SpacQuiz3.png
  public/assets/images/SpacQuiz/SpacQuiz4.png
  public/assets/images/SpacQuiz/SpacQuiz5.png
  public/assets/images/SpacQuiz/SpacQuiz6.png
  public/assets/images/SpacQuiz/SpacQuiz7.png
  public/assets/images/SpacQuiz/SpacQuiz8.png
  public/assets/images/SpacQuiz/SpacQuiz9.png
Labels: feat

#64 Feat/#43/프로필 컴포넌트
  app/(route)/mypage/(components)/ApplyStatus.tsx
  app/(route)/mypage/(components)/ApplyStatusItem.tsx
  app/(route)/mypage/(components)/ApplyStatusTable.tsx
  app/(route)/mypage/(components)/InterestingNotice.tsx
  public/assets/images/RightArrow.svg
Labels: feat

#66 Feat: AlarmDropDown 컴포넌트 제작
  app/components/Header/DropDown/AlarmDropDown.tsx
  app/components/Header/FolioHeader.tsx
  public/assets/images/Eye.svg
  public/assets/images/Setting.svg
Labels: feat

#67 Feat/#63/포트폴리오 메인 페이지
  app/(route)/portfolio/(components)/PortfolioBannerCarousel.tsx
  app/(route)/portfolio/(components)/PortfolioUserCard.tsx
  app/(route)/portfolio/(components)/PortfolioUserSection.tsx
  app/(route)/portfolio/layout.tsx
  app/(route)/portfolio/page.tsx
  app/style/PortfolioOwnerCarousel.module.css
Labels: feat

#69 Feat/#65/메인페이지 프로젝트 섹션
  app/(route)/main/(components)/FindProjectCard/ProjectMatchingBanner.tsx
  app/(route)/main/(components)/ProjectCard/MemberRecruitTag.tsx
  app/(route)/main/(components)/ProjectCard/ProjectCard.tsx
  app/(route)/main/(components)/ProjectCard/ProjectTypeTag.tsx
  app/(route)/main/(components)/SectionHeader.tsx
  app/(route)/main/page.tsx
  app/(route)/mypage/(components)/ApplyStatus.tsx
Labels: feat, style

#72 CommunityDetailPage 추가
  app/(route)/community/(components)/CommunityMenu.tsx
  app/(route)/community/[id]/(components)/CommunityDetailLikeAndSaveButton.tsx
  app/(route)/community/[id]/(components)/CommunityDetailTag.tsx
  app/(route)/community/[id]/page.tsx
  app/components/Icons/MessageIcon.tsx
  public/assets/images/Add.svg
  public/assets/images/Bookmark.svg
  public/assets/images/Close.svg
  public/assets/images/Frame.svg
  public/assets/images/HeartIcon.svg
Labels: feat
